import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import { AuthProvider } from "./context/AuthContext";
const poopins = Poppins({
  variable: "--font-poopins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});


export const metadata: Metadata = {
  title: "E-commerce",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${poopins.variable} h-full antialiased`}
    >
      <head>
    <link href="lib/animate/animate.min.css" rel="stylesheet"/>
      </head>
      <body className="min-h-full flex flex-col">
        <AuthProvider>
          <Navbar />
          <div className="mx-auto w-full max-w-9xl px-4 sm:px-6 lg:px-8">

          {children}
          </div>
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
